meta_product_name: "Brunchtime"
meta_title: "Brunchtime - Queue no more!"
meta_description: "An app for those who like to have brunch and wait the least possible time in line."
meta_image: "brunch-table1200x630.jpg"
